version: "3.9"
services:
  app_dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEVCONTAINER_OS: ubuntu-22.04
    ports:
      - ${APP_PORT:-8080}:${APP_PORT:-8080}
    volumes:
      - ..:/workspace:cached
      - app-dev-node-modules:/workspace/node_modules
    # env_file:
    #   - ../.env
    command: sleep infinity
    init: true
    networks:
      - redis

  redis:
    image: redis:7.2.1-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD:-password} # update if want persistance
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - redis

  redis-commander:
    platform: linux/amd64 # does not have support for ARM
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-password}
      HTTP_USER: ${REDISCOMMANDER_USER:-admin}
      HTTP_PASSWORD: ${REDISCOMMANDER_PASSWORD:-password}
    ports:
      - 8081:8081
    networks:
      - redis

networks:
  redis:
    driver: bridge

volumes:
  app-dev-node-modules:
